### ISSUE TITLE
create an active order with params from the front end

### ISSUE THREAD

**Issue by Sovamorco** [AtriEx/ATX#63]
create an api call that creates an active order based on params passed in from a form in the front end and inserts it into the active buy sell table

---

Imported from trello
Members: joshsteubs

**Comment by Sovamorco** [comment]
Imported from trello
Original author: joshsteubs

---

From discord discussion:

[https://fastapi.tiangolo.com/tutorial/query-params/#query-parameter-type-conversion](https://fastapi.tiangolo.com/tutorial/query-params/#query-parameter-type-conversion "smartCard-inline")

Looked into this a bit and seems like for query params that fastAPI will do much of this conversion for us.

[http://127.0.0.1:8000/items/foo?short=True](http://127.0.0.1:8000/items/foo?short=True "‌")

So for this, if we set the type hints correctly, short gets converted to a bool when backend receives it in the query param.

**Comment by Sovamorco** [comment]
Imported from trello
Original author: joshsteubs

---

From discord discussion:

[https://fastapi.tiangolo.com/tutorial/query-params/#query-parameter-type-conversion](https://fastapi.tiangolo.com/tutorial/query-params/#query-parameter-type-conversion "smartCard-inline")

Looked into this a bit and seems like for query params that fastAPI will do much of this conversion for us.

[http://127.0.0.1:8000/items/foo?short=True](http://127.0.0.1:8000/items/foo?short=True "‌")

So for this, if we set the type hints correctly, short gets converted to a bool when backend receives it in the query param.

**Comment by steubs** [comment]
not sure if i need repo access to assign myself here. currently dont see the option
